### PR TITLE
Remove rollup configs for internal builds

### PR DESCRIPTION
**Pull request by necolas**
Internally we could use patch files to rewrite the stylex import on web, and add the comment directives to exclude the files from linting/formatting, etc.

### CODE REVIEW

**Review by nmn — APPROVED** [review]
FWIW, I think it's worth removing Rollup for all builds.

**Comment by necolas** [comment]
The bundles are generally smaller when pre-built, as we found with React. And this also allows us to have CI accurately monitor the size of the library.

**Comment by nmn** [comment]
> The bundles are generally smaller when pre-built, 

Once the end user bundles, they'd get the same benefits? But having individual files helps if you're only use parts of the package.

We could keep generating a bundle specifically for CI?

**Comment by necolas** [comment]
You can't use this library as individual files. I don't see a benefit in trying to remove bundling only to keep it for CI. I think the current approach is straightforward and works

**Pull request merged**
